version: '3.9'

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=link
      - DB_PASSWORD=password
      - DB_NAME=link
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=link
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/init.sql
