version: '3.9'

services:
  api:
    build: .
    depends_on:
      - db
    expose:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://link:link@db:5432/links
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: link
      POSTGRES_USER: link
